title: Kartik Kumar
description: Final-year BTech CSE | Full-Stack Developer | React • Spring Boot • SQL

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

# Optional: choose a skin (minima has several nicer ones)
minima:
  skin: solarized   # or classic, dark, auto (tries system preference)
show_downloads: false
